### ISSUE TITLE
Error on M2.4

### ISSUE THREAD

**Issue by JelleGe** [yireo/magento2-replace-all#15]
When installing  the module using composer on Magento 2.4, we face the following errors;

  Problem 1
    - yireo/magento2-replace-all 3.5.2 requires magento/product-community-edition ~2.3.5 -> satisfiable by magento/product-community-edition[2.3.5-p2, 2.3.5-p1, 2.3.5] but these conflict with your requirements or minimum-stability.
    - yireo/magento2-replace-all 3.5.0 requires magento/product-community-edition 2.3.5 || 2.3.5-p1 -> satisfiable by magento/product-community-edition[2.3.5-p1, 2.3.5] but these conflict with your requirements or minimum-stability.
    - paypal/module-braintree-core 4.1.0 conflicts with yireo/magento2-replace-all[3.5.1].
    - yireo/magento2-replace-all 3.5.1 conflicts with paypal/module-braintree-core[4.1.0].
    - yireo/magento2-replace-all 3.5.1 conflicts with paypal/module-braintree-core[4.1.0].
    - Installation request for yireo/magento2-replace-all ^3.5 -> satisfiable by yireo/magento2-replace-all[3.5.0, 3.5.1, 3.5.2].
    - Installation request for paypal/module-braintree-core (locked at 4.1.0) -> satisfiable by paypal/module-braintree-core[4.1.0].

**Comment by jissereitsma** [comment]
Could you try again but double-check that you are installing version 4.0.0 of this package and not the 3.5.* package? The 4.0 package is meant for Magento 2.4: https://github.com/yireo/magento2-replace-all/blob/4.0.0/composer.json#L5

**Comment by JelleGe** [comment]
Seems that we indeed loaded the 3.5 version. But we now get the following 4.0 errors;

  Problem 1
    - paypal/module-braintree-core 4.1.0 conflicts with yireo/magento2-replace-all[4.0.0].
    - yireo/magento2-replace-all 4.0.0 conflicts with paypal/module-braintree-core[4.1.0].
    - yireo/magento2-replace-all 4.0.0 conflicts with paypal/module-braintree-core[4.1.0].
    - Installation request for yireo/magento2-replace-all 4.0.0 -> satisfiable by yireo/magento2-replace-all[4.0.0].
    - Installation request for paypal/module-braintree-core (locked at 4.1.0) -> satisfiable by paypal/module-braintree-core[4.1.0]

**Comment by jissereitsma** [comment]
Could you mention the commands and steps that lead to this output? See also the troubleshooting section here: https://github.com/yireo/magento2-replace-tools

**Comment by JelleGe** [comment]
We used the following command; composer require yireo/magento2-replace-all:4.0.0. But it seems that some modules are required in M2.4, that's causing the errors.

**Comment by jissereitsma** [comment]
The chance that you run into issues with the simple `composer require` command are huge and documented. Could you try out the alternatives as well?

**Comment by jissereitsma** [comment]
I'll close this for now. Let me know if the documented installation (removing the `composer.lock` and `vendor` instead of using the `require` because that does not work) still gives you issues.
