### ISSUE TITLE
magento 2.4.0 - elasticsearch 5/6 deprecated

### ISSUE THREAD

**Issue by magenx** [yireo/magento2-replace-all#16]
as ElasticSearch is up to version 7.x only, it is better to remove:
```
magento/module-elasticsearch
magento/module-elasticsearch-6
```

**Comment by jissereitsma** [comment]
Thanks, adding this right away.

**Comment by jissereitsma** [comment]
Actually, this turned out to be a bad idea. The module `magento/module-elasticsearch` is needed for the DI compilation of `magento/module-elasticsearch7`. And likewise, `magento/module-elasticsearch6` is still quite a bit used by the community.

**Comment by magenx** [comment]
i love magento
elasticsearch depends on elasticsearch to make elasticsearch work, but.... it is deprecated... 

https://devdocs.magento.com/guides/v2.3/mrg/ce/Elasticsearch.html
https://devdocs.magento.com/guides/v2.3/mrg/ce/Elasticsearch7.html

![magentoelk](https://user-images.githubusercontent.com/1591200/91025248-06ab7380-e5f1-11ea-9e9d-2adbe06090a0.png)

**Comment by jissereitsma** [comment]
I know. It apparently means that there is a difference between the ElasticSearch module (which supports both the deprecated options plus the interfaces needed for the other modules) and the actual selection for a search engine.

**Comment by magenx** [comment]
sure... this is exactly how it supposed to work 🥇

**Comment by magenx** [comment]
magento 2.4.0 fresh install

![magentoelk](https://user-images.githubusercontent.com/1591200/91055154-30c65b00-e61c-11ea-873d-a544225f0262.png)

**Comment by jissereitsma** [comment]
Again, I understand - you don't need to proof this, I already understood. But *deprecated* does not mean that this change should be enforced upon everyone. 

I assume you are well aware of the fact that this replacement package is a kickstart for anyone willing to remove packages using an undocumented hack in composer. But also note that if you disagree with anything here, the simple and adequate solution is to copy the replace sections to your own project and replace things there. In short, if you want to remove the ES and ES6 module, you can do so by adding the replacements to your own composer project. But I do not think it is a wise idea to enforce this change upon the other users of this package. Nothing more, nothing less.
