### ISSUE TITLE
Replace missing

### ISSUE THREAD

**Issue by antonfries** [yireo/magento2-replace-all#20]
"magento/module-catalog-rule-graph-ql" is missing in 2.3.6.

**Comment by jissereitsma** [comment]
Thanks. Please note that you can also make a Pull Request just as easily. It would streamline things even more. Just edit the `composer.json` in the GitHub pages and you're done: https://github.com/yireo/magento2-replace-all/commit/67f2e535ab30dd157444e7abe0de31720a9fe27b
