### ISSUE TITLE
Error on M2.4.2

### ISSUE THREAD

**Issue by JelleGe** [yireo/magento2-replace-all#21]
We face the following issue on M2.4.2 when we running the `bin/magento setup:di:compile` command. 

```
Class Magento\InventorySalesApi\Api\StockResolverInterface does not exist                                                                                    
  Class Magento\InventoryCatalogFrontendUi\Controller\Product\GetQty\Interceptor generation error: The requested class did not generate properly, because the  
   'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permissi  
  on is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construc  
  t method, only.              
```

And it also seem that this pack is missing some elements that can be find in the individual packs, like `magento/module-inventory-wishlist` for example.

**Comment by jissereitsma** [comment]
This should be fixed now with version 4.2.1 https://github.com/yireo/magento2-replace-all/blob/magento-2.4.2/composer.json#L127 Out of interest, are you going into production with this? This package is meant as a validation package, but there are few people that actually use it in production ...

**Comment by JelleGe** [comment]
Thanks! That indeed solved the issue. Yes we are gonna use it in production, because we really hate the Magento Inventory module, especially the requirements to ship an order and the check for stock at the same time.

**Comment by jissereitsma** [comment]
Ok, but note that this specific repository removes about 3x more than just the inventory. For the inventory, there is a separate package - just follow the READMEs.
