### ISSUE TITLE
Magento 2.3.7, 2.3.7-p1, 2.3.7-p2

### ISSUE THREAD

**Issue by itagil** [yireo/magento2-replace-all#25]
Is it planned to add support of 2.3.7 versions?
  Problem 1
    - Conclusion: remove magento/product-community-edition 2.3.7-p2
    - Conclusion: don't install yireo/magento2-replace-all 3.6.2
    - Installation request for magento/product-community-edition 2.3.7-p2 -> satisfiable by magento/product-community-edition[2.3.7-p2].
    - Conclusion: don't install yireo/magento2-replace-all 3.6.1
    - magento/product-community-edition 2.3.7-p2 requires yotpo/magento2-module-yotpo-reviews-bundle 3.1.0-p3 -> satisfiable by yotpo/magento2-module-yotpo-reviews-bundle[3.1.0-p3].
    - don't install yotpo/magento2-module-yotpo-reviews-bundle 3.1.0-p3|don't install yireo/magento2-replace-all 3.6.0
    - don't install yireo/magento2-replace-all 3.6.0|remove yotpo/magento2-module-yotpo-reviews-bundle 3.1.0-p3
    - Installation request for yireo/magento2-replace-all ^3.6 -> satisfiable by yireo/magento2-replace-all[3.6.0, 3.6.1, 3.6.2].

**Comment by jissereitsma** [comment]
I'm unable to test things myself, but the `composer.json` file of the 3.6.2 release shows the following: https://github.com/yireo/magento2-replace-all/blob/3.6.2/composer.json#L5 So this should match anything with 2.3.*. So this issue does not seem to be related to 2.3.7 with any patches.

Did you make sure to remove `vendor/` and `composer.lock` to troubleshoot things?

**Comment by itagil** [comment]
Ok. Thanks.
I have solved it directly in my composer.json.

**Comment by jissereitsma** [comment]
Could you let us know the fix? If your claim is correct, then something was wrong with these replacements, meaning that others might bump into things as well. So if you could comment upon your fix, others can benefit as well.

**Comment by itagil** [comment]
@jissereitsma 
I have placed replace section form (https://github.com/yireo/magento2-replace-all/blob/magento-2.3/composer.json )directly in my composer.json. Also, I have added vertexinc/sdk extension to the list because it was in my 2.3.7 Open Source version. After this, I was able to uninstall optional modules.

**Comment by jissereitsma** [comment]
Thanks. That's strange that it wouldn't work through this package. The line https://github.com/yireo/magento2-replace-all/blob/magento-2.3/composer.json#L221 shows `vertexinc/sdk` is already replaced. I have also tested this out manually on a 2.3.7 site myself and it just works. Anyway, you solved it. Glad to hear that it worked out.
