### ISSUE TITLE
Exclude specific module from being replaced?

### ISSUE THREAD

**Issue by Aquive** [yireo/magento2-replace-all#26]
Hi,

What is the best approach to exclude a specific module from being excluded? In my case, `magento/module-customer-import-export`. Just tried to overrule the replace with a `require magento/module-customer-import-export` which doesn't work, unfortunately.

Is there an easy way? What is the advised approach?

**Comment by jissereitsma** [comment]
You can't. Copy the `replace` rules of this meta-package in your own `composer.json` and then modify it at will ...

**Comment by Aquive** [comment]
Thanks for your reply!
